sudo: required
dist: trusty
language: generic

env:
  - SUITE=system2
#  - SUITE=system2 ALBA_TLS=true
  - SUITE=disk_failures
  - SUITE=recovery

before_install: ./travis.sh before_install
install:        ./travis.sh install
script:         ./travis.sh script
