sudo: required
dist: trusty
language: generic

env:
  - SUITE=ocaml
#  - SUITE=ocaml ALBA_TLS=true
  - SUITE=disk_failures
  - SUITE=recovery

install:        ./travis.sh install
script:         ./travis.sh script

services:
  - docker

cache:
  directories:
    - ~/cache
  timeout:
    1000
